apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cbcore.aks.kearos.net
  namespace: jx-production
spec:
  secretName: tls-cbcore-aks-kearos-net
  dnsNames:
  - cbcore.aks.kearos.net
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - cbcore.aks.kearos.net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
