dependencies:
- name: exposecontroller
  version: 2.3.89
  repository: http://chartmuseum.jenkins-x.io
  alias: expose
- name: exposecontroller
  version: 2.3.89
  repository: http://chartmuseum.jenkins-x.io
  alias: cleanup
- name: cloudbees-core
  version: 2.176.203
  repository: https://charts.cloudbees.com/public/cloudbees
  alias: cbcore
- name: opendj4
  version: 0.2.0
  repository: https://raw.githubusercontent.com/joostvdg/helm-repo/master/
  alias: ldap
